# Generated by Django 5.1.1 on 2024-09-30 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Food', 'Food'), ('Dessert', 'Dessert')], default='food', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='country',
            field=models.CharField(choices=[('Fayoum', 'Fayoum'), ('Cairo', 'Cairo'), ('Alexandria', 'Alexandria')], default='cairo', max_length=50),
            preserve_default=False,
        ),
    ]
